//! Generated gateway bootstrap for sdkwork-portal.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_portal_service_host::PortalServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(host: Arc<PortalServiceHost>) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_portal_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_portal_backend_api::gateway_mount(host).await);
    ApplicationAssembly { router }
}
